[tool.poetry]
name = "RoboShpee"
version = "1.0.0"
description = ""
authors = ["KGB33 <github@bassingthwaite.org>"]

[tool.poetry.dependencies]
python = "^3.11"
"discord.py" = {extras = ["voice"], version = "^2.0.1"}
prettytable = "^2.0.0"
fuzzywuzzy = {extras = ["speedup"], version = "^0.18.0"}
requests = "^2.25.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.8.2"
black = "^20.8b1"
pylint = "^2.6.0"
pytest = "^6.2.1"
hypothesis = "^5.43.5"
isort = "^5.9.2"
dagger-io = "^0.1.1"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
multi_line_output = 3
