[tool.poetry]
name = "RoboShpee"
version = "1.0.0"
description = ""
authors = ["KGB33 <github@bassingthwaite.org>"]

[tool.poetry.dependencies]
python = "^3.11"
"discord.py" = "^2.1.1"
prettytable = "^3.5.0"
fuzzywuzzy = {extras = ["speedup"], version = "^0.18.0"}
requests = "^2.28.1"
cashews = "^5.2.0"
charset-normalizer = "^3.0.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.4"
black = "^23.1.0"
pylint = "^2.16.1"
pytest = "^7.2.0"
hypothesis = "^6.68.0"
isort = "^5.12.0"
dagger-io = "^0.3.2"
poethepoet = "^0.18.1"
pytest-asyncio = "^0.20.2"
pytest-check = "^2.1.3"
ruff = "^0.0.244"
astroid = "^2.14.1"
identify = "^2.5.17"
mypy-extensions = "^1.0.0"
platformdirs = "^3.0.0"
setuptools = "^67.2.0"
virtualenv = "^20.19.0"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.ruff]
select=["E", "F", "I",]
fix=true

[tool.poe.tasks]
test = "pytest"
fmt = [
	{cmd="black ."}
]
lint = [
	{cmd="ruff ."},
	"fmt",
]
build = "python build.py"
run = "python -m roboshpee"
