name: "Build & Push Container Image"

# Only a single job with this concurrency can run at any given time
concurrency: release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
permissions:
  packages: write
  actions: write
jobs:
  publish:
    name: "Build & Push to GHCR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Tests
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          args: "test --req pyproject.toml --src roboshpee/ --tests tests/"
          version: "0.11.3"
      - name: Publish to GHCR
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          args: "publish --req pyproject.toml --src roboshpee/ --ghcr-token env:GH_TOKEN"
          version: "0.11.3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
