name: "Run tests for PRs"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  publish:
    name: "Run tests for PRs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Tests
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          args: "test --req pyproject.toml --src roboshpee/ --tests tests/"
          version: "0.11.3"
